# Generated by Django 4.0.6 on 2022-07-27 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_action_newsfeed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsfeed",
            name="to_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_news_feed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
