# Generated by Django 4.0.6 on 2022-07-28 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_newsfeed_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsfeed",
            name="action",
        ),
        migrations.DeleteModel(
            name="Action",
        ),
    ]
