# Generated by Django 4.0.6 on 2022-08-02 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_choice_votes_remove_reply_likes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="question",
        ),
    ]
