# Generated by Django 4.0.6 on 2022-08-02 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_vote_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likes",
            name="reply",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.reply",
            ),
        ),
        migrations.AlterField(
            model_name="likes",
            name="tweet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.tweet",
            ),
        ),
    ]
