# Generated by Django 4.0.6 on 2022-09-01 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_vote_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.choice"
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
