# Generated by Django 4.0.6 on 2022-09-01 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_vote_choice_alter_vote_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likes",
            name="reply",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="accounts.reply",
            ),
        ),
        migrations.AlterField(
            model_name="likes",
            name="tweet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="accounts.tweet",
            ),
        ),
    ]
